spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${secrets.local.datasource.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${secrets.local.datasource.username}
    password: ${secrets.local.datasource.password}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  jackson:
    time-zone: Asia/Seoul

  h2:
    console:
      enabled: false

product:
  policy:
    deliveryInfo: "기본 배송 정책: 평일 1-2일 배송"
    refundPolicy: "기본 환불 정책: 수령 후 7일 이내 미개봉 상태에서만 가능"
  image-upload:
      bucket: drop-product-image-574070665489-ap-northeast-2-an  # 생성한 버킷 이름
      region: ap-northeast-2
      key-prefix: products
      cdn-base-url: https://drop-product-image-574070665489-ap-northeast-2-an.s3.ap-northeast-2.amazonaws.com
      presigned-expiration-seconds: 300

aws:
  credentials:
    access-key: ${secrets.aws.access-key}
    secret-key: ${secrets.aws.secret-key}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
